articles/urls.py
from django.urls import path

from .views import ArticleCreateView, ArticlesListView


app_name = 'articles'

urlpatterns = [
	path('', ArticlesListView.as_view(), name='articles'),
	path('create/', ArticleCreateView.as_view(), name='create_article'),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls'), name='home_page'),
]

articles/models.py
from django.db import models


class Article(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	pub_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-pub_date']


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	author_name = models.CharField(max_length=100)
	comment_text = models.TextField()
	pub_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.author_name

	class Meta:
		ordering = ['article']

articles/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']

articles/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .forms import ArticleForm
from .models import Article


class ArticlesListView(ListView):
	model = Article
	

class ArticleCreateView(CreateView):
	model = Article
	form_class = ArticleForm
	success_url = reverse_lazy('articles:articles')
 

articles/templates/articles/article_form.html
{% extends 'base.html' %}


{% block title %}
    Add new article
{% endblock %}


{% block content %}

	<form action="" method="POST">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Save">
	</form>
	
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}


{% block title %}
    Add new article
{% endblock %}


{% block content %}

    {% if object_list %}
        <h1>Articles:</h1>
        {% for object in object_list %}
            <h3>{{ object.title }}</h3>
            <p>{{ object.text }}</p>
            <p style="color: grey">{{ object.pub_date }}</p>
        {% endfor %}
    {% else %}
        <h3>No articles</h3>
    {% endif %}

    <button>
        <a href="{% url 'articles:create_article' %}">Create new article</a>
    </button>
    
{% endblock %}

articles/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- CSS -->
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/styles.css' %}">

	<title>{% block title %}{% endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}

</body>
</html>